spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 4s
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
    info:
      env:
        enabled: true

info:
  title: ${INFO_TITLE:gatewayserver}
  version: ${INFO_VERSION:1.0.0}
  description: ${INFO_DESCRIPTION:Eazy Bank Gateway Server application}

server:
  port: 8780