spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 4s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
    info:
      env:
        enabled: true

info:
  title: ${INFO_TITLE:gatewayserver}
  version: ${INFO_VERSION:1.0.0}
  description: ${INFO_DESCRIPTION:Eazy Bank Gateway Server application}

server:
  port: 8780

springdoc:
    urls:
      - name: User Service
        url: /aggregate/users-service/v3/api-docs
      - name: Event Service
        url: /aggregate/event-service/v3/api-docs

