spring:
  application:
    name: "gatewayserver"
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8888/}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 4s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  main:
    allow-bean-definition-overriding: true


info:
  title: ${INFO_TITLE:gatewayserver}
  version: ${INFO_VERSION:1.0.0}
  description: ${INFO_DESCRIPTION:Eazy Bank Gateway Server application}


springdoc:
    urls:
      - name: User Service
        url: /aggregate/users-service/v3/api-docs
      - name: Event Service
        url: /aggregate/event-service/v3/api-docs

