server:
  port: 8761

spring:
  application:
    name: ${APPLICATION_NAME:eurekaserver}

eureka:
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
