spring:
  application:
    name: ${SPRING_APP_NAME:events}
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8888/}
  datasource:
    url: jdbc:mysql://${DATABASE_HOSTNAME:localhost}:${DATABASE_PORT:3311}/${DATABASE_NAME:EventDB}
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${JWT_SET_URI:http://localhost:8081/realms/eventmanagmentplatform/protocol/openid-connect/certs}

info:
  app:
    name: "events"
    description: "Event System Events Microservice"
    version: "1.0.0"

