spring:
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8888/}
  application:
    name: ${APP_NAME:users}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3310}/${DATABASE_NAME:UserDB}
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/eventmanagmentplatform/protocol/openid-connect/certs}

keycloak:
  url: http://localhost:7070/auth/admin/realms/master"
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:60m}
  port: ${SERVER_PORT:8091}


info:
  app:
    name: "users"
    description: "Event System Users Microservice"
    version: "1.0.0"
