spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: "booking"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3312}/${DATABASE_NAME:BookingDB}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Sqlwer}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

server:
  port: 8010
info:
  app:
    name: "users"
    description: "Event System Users Microservice"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
